Adding footer to html file
IanHooper613/Project-1 pull request #28
Opened 2020-03-26 23:37 UTC by IanHooper613

2020-03-26 23:41 UTC, mscoulte requested changes
Add styling

2020-03-27 00:15 UTC, mscoulte submitted a review, later dismissed

2020-03-27 00:25 UTC, MitoKito commented on index.html
> +              <img src="https://bulma.io/images/placeholders/128x" class="" alt="Image">
Revert this line change

2020-03-27 00:28 UTC, MitoKito commented on index.html
> +  <footer class="footer">
Move this to the body

2020-03-27 00:51 UTC, miitodev approved these changes

2020-03-27 00:51 UTC, mscoulte approved these changes

2020-03-27 00:52 UTC, merged